### ISSUE TITLE
CSAE Model

### ISSUE THREAD

**Issue by HieuPhan33** [HieuPhan33/LCFS-BERT#2]
Hi all,
I don't intend to open-source the CSAE model, so the code is really messy.

You can find my source code in the google drive link.
https://drive.google.com/file/d/1FBBucbUgj9GfKzp3WDWZBKT6dNu0EDPZ/view?usp=sharing

Please run the script src/run_ae.py as:

python ../src/run_ae.py \ --bert_model bert --do_train --do_valid \ --max_seq_length 100 --train_batch_size 32 --learning_rate 3e-5 --num_train_epochs 4 \ --output_dir $OUTPUT_DIR --data_dir $DATA_DIR

The CSAE model is the class BertForSequenceLabeling in model.py.
It uses the dependency-word embedding in "/ae/emb.npy".

Those are some basic usage about the model.

**Comment by vishnu-itachi** [comment]
Thanks for sharing the code. I have one question. Since you are using Roberta or Bert pretrained model. Do you really need to train for 200 epochs as given in the above code? . I am obtaining almost all results close to paper with 5 or 10 epochs. Thanks

**Comment by HieuPhan33** [comment]
Thanks for your notice, the performance can converge with less than 20 epochs.

**Comment by vishnu-itachi** [comment]
Thanks for the info. I encountered a specific problem. I am using Bertforsequence labeling with both pos and DEP embeddings removed. When I try to run I get the error "The hidden size (768) is not a multiple of the number of attention heads (10)".
This because in src/model.py in line 201
```
out_attention_config = BertConfig(hidden_size=hidden, num_attention_heads=10,attention_probs_dropout_prob=0.1)
```
Here the attention heads are 10 and 768 is not multiple of 10. The problem is mentioned here [Why hidden size must be a multiple of the number of attention head](https://github.com/google-research/bert/issues/316)

The same problem arises when you do the same experiment with only bert and dep embeddings. In this case, the hidden size becomes 1068 (768 +300). Hence I believe the parameter in that line is dependent on config rather than a constant value.

I am a bit confused. Will be grateful if you clarify. Thanks

**Comment by HieuPhan33** [comment]
I admit that we need to adjust the `num_attention_heads` manually when doing ablation study (using only parts of the model). Please calculate the expected `hidden_size` in advance and choose the `num_attention_heads` as a factor of `hidden_size` between 10 to 20 for optimal performance (just based on my own experience).

For the case of BERT + Dep embeddings, you can try to set the num_attention_heads = 12 (which is a factor of 1068).

**Comment by vishnu-itachi** [comment]
Thanks for the quick reply. That's what I did.
